### ISSUE TITLE
Not longer working on Kodi 20

### ISSUE THREAD

**Issue by aburke20** [teaguecl/delete_after_watching#1]
Get a message saying to check log,
this is all I can find:

File "C:\Users\xxx\AppData\Roaming\Kodi\addons\script.service.daw\service.py", line 33, in <module>
                                                       from resources.lib import util
                                                     File "C:\Users\xxx\AppData\Roaming\Kodi\addons\script.service.daw\resources\lib\util.py", line 29, in <module>
                                                       profile = xbmc.translatePath(__ADDON.getAddonInfo('profile'))
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--

Wish I knew how to fix it myself :(

**Comment by aburke20** [comment]
WOOOOHOOO, BABY !! managed to fix it all by myself.

OK, so, I googled "AttributeError: module 'xbmc' has no attribute 'translatePath'", and the very first result was someone showing exactly how to fix it, and the second one was someone explaining why it needed to be fixed: "In latest Kodi 19 [and 20 I guess], the validatePath function has been moved from xbmc to xbmcvfs resulting in an error."

So, using the original kodi log error, I found util.py, opened it up, and on line 29 simply switched

profile = **xbmc**.translatePath(__ADDON.getAddonInfo('profile'))

to

profile = **xbmcvfs**.translatePath(__ADDON.getAddonInfo('profile'))

Hey presto, it works again ! Yay, so proud of myself.

Hope this helps anyone else out there still using this years-old addon

**Comment by teaguecl** [comment]
While I haven't used this addon (or KODI) for years, your ticket here inspired me to take a look.  I only ran it with Kodi 19.4 as that's the latest in Debian, but there were several issues I ran into in addition to the one you point out.  I released a new version (0.0.4) with some small fixes, but not change to functionality.
